// Environment configuration example
// Copy this file to email-config.js and update with your settings

const emailConfig = {
  // ===== SMTP CONFIGURATION =====
  // Gmail (recommended)
  smtp: {
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    auth: {
      user: 'your-email@gmail.com', // Replace with your Gmail
      pass: 'abcd-efgh-ijkl-mnop' // Replace with 16-char app password
    }
  },

  // Alternative: Outlook/Hotmail
  // smtp: {
  //   host: 'smtp-mail.outlook.com',
  //   port: 587,
  //   secure: false,
  //   auth: {
  //     user: 'your-email@outlook.com',
  //     pass: 'your-password'
  //   }
  // },

  // ===== RECIPIENTS =====
  recipients: [
    'customer@company.com',
    'qa-manager@company.com',
    'dev-team@company.com'
  ],

  // ===== EMAIL SETTINGS =====
  from: '"Login Test Automation" <your-email@gmail.com>',
  subject: '🔐 Login Test Report - {date}',

  // ===== EMAIL TEMPLATE =====
  getEmailBody: (stats, reportPath) => {
    const { passed, failed, total, totalRetries, executionTime } = stats;
    const passRate = ((passed / total) * 100).toFixed(2);

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { padding: 20px; background: #f9f9f9; border-radius: 0 0 8px 8px; }
        .metrics { display: flex; justify-content: space-around; margin: 20px 0; }
        .metric { text-align: center; padding: 15px; background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .metric h3 { margin: 0; font-size: 2em; }
        .metric-passed { border-left: 4px solid #28a745; }
        .metric-failed { border-left: 4px solid #dc3545; }
        .metric-total { border-left: 4px solid #007bff; }
        .btn { display: inline-block; padding: 12px 24px; background: #007bff; color: white; text-decoration: none; border-radius: 5px; margin: 10px 0; }
        .footer { text-align: center; font-size: 0.9em; color: #666; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🔐 Login Automation Test Report</h1>
        <p>Automated testing completed successfully</p>
    </div>

    <div class="content">
        <h2>📊 Test Summary</h2>

        <div class="metrics">
            <div class="metric metric-total">
                <h3>${total}</h3>
                <p>Total Tests</p>
            </div>
            <div class="metric metric-passed">
                <h3>${passed}</h3>
                <p>Passed</p>
            </div>
            <div class="metric metric-failed">
                <h3>${failed}</h3>
                <p>Failed</p>
            </div>
        </div>

        <p><strong>Pass Rate:</strong> ${passRate}%</p>
        <p><strong>Total Retries Used:</strong> ${totalRetries}</p>
        <p><strong>Execution Time:</strong> ${executionTime}</p>

        <h3>📋 Report Contents:</h3>
        <ul>
            <li>✅ Detailed test results with screenshots</li>
            <li>✅ Visual status indicators</li>
            <li>✅ Retry attempts and failure analysis</li>
            <li>✅ Professional presentation</li>
        </ul>

        <a href="cid:report-attachment" class="btn">📄 View Full Report</a>

        <div class="footer">
            <p>This report was automatically generated by the Login Automation Framework</p>
            <p>For questions or support, contact the QA team</p>
        </div>
    </div>
</body>
</html>`;
  }
};

module.exports = emailConfig;