// Email configuration for automated report delivery
const emailConfig = {
  // SMTP Configuration - UPDATE WITH YOUR ACTUAL CORPORATE SMTP SETTINGS
  smtp: {
    host: 'smtp.digitide.com', // Replace with your actual SMTP server (e.g., smtp.office365.com, mail.digitide.com)
    port: 587, // Common ports: 587 (TLS), 465 (SSL), 25 (non-secure)
    secure: false, // true for 465, false for 587/25
    auth: {
      user: 'sasikala.k@digitide.com', // Your corporate email
      pass: 'your-actual-corporate-password' // Your corporate email password
    }
  },

  // Email Recipients
  recipients: [
    'sasikala.k@digitide.com'  // Your corporate email - reports will be sent here
  ],

  // Email Content
  from: '"Login Automation Bot" <sasikala.k@digitide.com>',
  subject: '🔐 Login Automation Test Report - {date}',

  // Email Template
  getEmailBody: (stats, reportPath) => {
    const { passed, failed, total, totalRetries, executionTime } = stats;
    const passRate = ((passed / total) * 100).toFixed(2);

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { padding: 20px; background: #f9f9f9; border-radius: 0 0 8px 8px; }
        .metrics { display: flex; justify-content: space-around; margin: 20px 0; }
        .metric { text-align: center; padding: 15px; background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .metric h3 { margin: 0; font-size: 2em; }
        .metric-passed { border-left: 4px solid #28a745; }
        .metric-failed { border-left: 4px solid #dc3545; }
        .metric-total { border-left: 4px solid #007bff; }
        .btn { display: inline-block; padding: 12px 24px; background: #007bff; color: white; text-decoration: none; border-radius: 5px; margin: 10px 0; }
        .footer { text-align: center; font-size: 0.9em; color: #666; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🔐 Login Automation Test Report</h1>
        <p>Automated testing completed successfully</p>
    </div>

    <div class="content">
        <h2>📊 Test Summary</h2>

        <div class="metrics">
            <div class="metric metric-total">
                <h3>${total}</h3>
                <p>Total Tests</p>
            </div>
            <div class="metric metric-passed">
                <h3>${passed}</h3>
                <p>Passed</p>
            </div>
            <div class="metric metric-failed">
                <h3>${failed}</h3>
                <p>Failed</p>
            </div>
        </div>

        <p><strong>Pass Rate:</strong> ${passRate}%</p>
        <p><strong>Total Retries Used:</strong> ${totalRetries}</p>
        <p><strong>Execution Time:</strong> ${executionTime}</p>

        <h3>📋 What to Expect:</h3>
        <ul>
            <li>✅ Detailed HTML report with screenshots</li>
            <li>✅ Visual test results and status indicators</li>
            <li>✅ Retry attempts and failure analysis</li>
            <li>✅ Professional presentation for stakeholders</li>
        </ul>

        <a href="cid:report-attachment" class="btn">📄 View Full Report</a>

        <div class="footer">
            <p>This report was automatically generated by the Login Automation Framework</p>
            <p>For questions or support, contact the QA team</p>
        </div>
    </div>
</body>
</html>`;
  }
};

module.exports = emailConfig;